version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
